package handlers

const (
	tagAuth             = "Auth"
	tagAccounts         = "Accounts"
	tagMedia            = "Media"
	tagPostingSchedules = "Posting Schedules"
	tagPosts            = "Posts"
	tagPrompts          = "Prompts"
	tagSets             = "Sets"
	tagWorkspaces       = "Workspaces"

	fieldError = "error"

	errWorkspaceIDRequired      = "workspace_id is required"
	errValidateWorkspaceAccess  = "failed to validate workspace access"
	errWorkspaceAccessDenied    = "you do not have access to this workspace"
	errMediaNotFound            = "media not found"
	mediaSortSize               = "size"
	postStatusPending           = "pending"
	postIDKey                   = "post_id"
	jobTypePublishPost          = "publish_post"
	postPathByID                = "/posts/{id}"
	postPathVariants            = "/posts/{id}/variants"
	setPathByID                 = "/sets/{id}"
	postingLabelEarlyMorning    = "Early Morning"
	postingLabelMorning         = "Morning"
	postingLabelLateMorning     = "Late Morning"
	postingLabelLunch           = "Lunch"
	postingLabelAfternoon       = "Afternoon"
	postingLabelLateAfternoon   = "Late Afternoon"
	postingLabelEvening         = "Evening"
	postingLabelNight           = "Night"
	postingLabelLateNight       = "Late Night"
	promptCategoryBoldProvoking = "Bold & Provoking"
	promptCategoryStorytelling  = "Storytelling"
	promptCategoryRepurposeFAQ  = "Repurpose & FAQ"
	promptCategoryDailyUpdates  = "Daily Updates"
	promptCategoryHowTo         = "How-To"
	promptCategoryReflection    = "Reflection"
	promptCategoryEngagement    = "Engagement"
	promptCategoryToolsWorkflow = "Tools & Workflow"
	promptCategoryBehindScenes  = "Behind the Scenes"
	promptCategoryWins          = "Wins"
	promptCategoryCuratedLists  = "Curated Lists"
	promptCategoryPredictions   = "Predictions"
	promptCategoryQuickEasy     = "Quick & Easy"
	promptCategoryDeveloper     = "Developer"
)
